import { EngineeringBranch, Project } from './types';

export interface BranchInfo {
  id: EngineeringBranch;
  name: string;
  fullName: string;
  badgeColor: string;
  gradient: string;
  iconName: string;
  description: string;
}

export const BRANCHES: BranchInfo[] = [
  {
    id: 'CSE',
    name: 'CSE',
    fullName: 'Computer Science & Engineering',
    badgeColor: 'bg-blue-500/10 text-blue-400 border-blue-500/20',
    gradient: 'from-blue-600 to-indigo-600',
    iconName: 'Code',
    description: 'Full-stack web applications, cloud systems, distributed databases, and mobile solutions.',
  },
  {
    id: 'IT',
    name: 'IT',
    fullName: 'Information Technology',
    badgeColor: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/20',
    gradient: 'from-cyan-600 to-blue-600',
    iconName: 'Server',
    description: 'Enterprise web systems, network security tools, and automated DevOps deployment suites.',
  },
  {
    id: 'AI_DS',
    name: 'AI & DS',
    fullName: 'Artificial Intelligence & Data Science',
    badgeColor: 'bg-purple-500/10 text-purple-400 border-purple-500/20',
    gradient: 'from-purple-600 to-pink-600',
    iconName: 'Brain',
    description: 'Data analytics, predictive forecasting engines, automated EDA pipelines, and Big Data platforms.',
  },
  {
    id: 'AIML',
    name: 'AI & ML',
    fullName: 'Artificial Intelligence & Machine Learning',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    gradient: 'from-emerald-600 to-teal-600',
    iconName: 'Cpu',
    description: 'Deep Learning models, Computer Vision, Natural Language Processing (NLP), and PyTorch projects.',
  },
  {
    id: 'CSE_DS',
    name: 'CSE (DS)',
    fullName: 'CSE (Data Science Specialization)',
    badgeColor: 'bg-amber-500/10 text-amber-400 border-amber-500/20',
    gradient: 'from-amber-600 to-orange-600',
    iconName: 'Database',
    description: 'Specialized statistical modeling, sentiment analysis dashboards, and machine learning pipelines.',
  },
];

export const DEMO_PROJECTS: Project[] = [
  {
    id: 'p1',
    title: 'AI Medical Diagnostics & X-Ray Analysis Platform',
    slug: 'ai-medical-diagnostics-xray-platform',
    branch: 'AIML',
    category: 'MAJOR_FINAL_YEAR',
    short_description: 'Deep Learning ResNet-50 CNN model for automated pneumonia & COVID-19 detection from chest X-rays with FastAPI backend & React dashboard.',
    full_description: `An end-to-end medical vision system designed for engineering final-year evaluation. Features a custom trained ResNet-50 Convolutional Neural Network achieving 96.4% validation accuracy on 10,000+ medical X-ray datasets. Includes Grad-CAM heatmaps showing exact lesion locations, FastAPI async inference engine, full IEEE format project report, and ready presentation slides.`,
    tech_stack: ['Python', 'PyTorch', 'ResNet-50', 'FastAPI', 'React', 'OpenCV'],
    price_inr: 2499,
    discounted_price_inr: 1499,
    thumbnail_url: '/images/aiml_medical_xray.jpg',
    demo_video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    file_path: 'projects/aiml-xray-diag.zip',
    is_published: true,
    is_featured: true,
    view_count: 1420,
    download_count: 89,
    includes_report: true,
    includes_ppt: true,
    includes_diagrams: true,
    created_at: '2026-09-01T00:00:00Z',
    updated_at: '2026-10-01T00:00:00Z',
  },
  {
    id: 'p3',
    title: 'Real-Time Driver Drowsiness & Yawn Detection System using OpenCV',
    slug: 'driver-drowsiness-yawn-detection-opencv',
    branch: 'AI_DS',
    category: 'MINI_PROJECT',
    short_description: 'Facial landmark facial EAR (Eye Aspect Ratio) calculator triggering real-time audio alerts for automotive safety.',
    full_description: `Mini project designed for AI&DS and CSE students. Detects driver eye closure and yawning frequencies using dlib 68-point facial landmark predictor. Triggers instant buzzer sound and logs drowsiness events with timestamps to an SQLite analytics database.`,
    tech_stack: ['Python', 'OpenCV', 'dlib', 'SciPy', 'Tkinter'],
    price_inr: 1499,
    discounted_price_inr: 899,
    thumbnail_url: '/images/aids_drowsiness.jpg',
    demo_video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    file_path: 'projects/aids-drowsiness.zip',
    is_published: true,
    is_featured: true,
    view_count: 2100,
    download_count: 145,
    includes_report: true,
    includes_ppt: true,
    includes_diagrams: true,
    created_at: '2026-09-10T00:00:00Z',
    updated_at: '2026-10-03T00:00:00Z',
  },
  {
    id: 'p5',
    title: 'Distributed E-Commerce Microservices Engine with Kafka & Docker',
    slug: 'distributed-ecommerce-microservices-kafka-cse',
    branch: 'CSE',
    category: 'MAJOR_FINAL_YEAR',
    short_description: 'Spring Boot & Next.js microservices architecture with Apache Kafka event-driven order processing, Redis caching, and Kubernetes deployment scripts.',
    full_description: `Comprehensive Software Engineering project for CSE & IT final year. Features API Gateway (Spring Cloud), Distributed Tracing (Zipkin), Order & Payment services communicating via Kafka event stream, PostgreSQL per service pattern, and full Docker Compose setup.`,
    tech_stack: ['Java Spring Boot', 'Apache Kafka', 'Next.js', 'Docker', 'PostgreSQL', 'Redis'],
    price_inr: 2799,
    discounted_price_inr: 1699,
    thumbnail_url: '/images/cse_microservices.jpg',
    demo_video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    file_path: 'projects/cse-microservices.zip',
    is_published: true,
    is_featured: true,
    view_count: 1780,
    download_count: 112,
    includes_report: true,
    includes_ppt: true,
    includes_diagrams: true,
    created_at: '2026-09-15T00:00:00Z',
    updated_at: '2026-10-05T00:00:00Z',
  },
  {
    id: 'p6',
    title: 'Customer Churn Prediction & Lifetime Value Analytics Pipeline',
    slug: 'customer-churn-prediction-data-science-pipeline',
    branch: 'CSE_DS',
    category: 'MAJOR_FINAL_YEAR',
    short_description: 'End-to-end Data Science pipeline using XGBoost, SHAP explainability analysis, Streamlit dashboard, and automated ETL data preprocessing.',
    full_description: `Tailored for CSE (Data Science) & AI&DS students. Analyzes 50,000+ telecom customer records to predict customer churn risk probability. Includes feature engineering scripts, model evaluation metrics (ROC-AUC, Precision-Recall), SHAP interpretability charts, Streamlit web app, and 45-page Word document report.`,
    tech_stack: ['Python', 'XGBoost', 'SHAP', 'Pandas', 'Streamlit', 'Scikit-Learn'],
    price_inr: 1899,
    discounted_price_inr: 1199,
    thumbnail_url: '/images/cseds_churn.jpg',
    demo_video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    file_path: 'projects/cseds-churn-pipeline.zip',
    is_published: true,
    is_featured: false,
    view_count: 720,
    download_count: 41,
    includes_report: true,
    includes_ppt: true,
    includes_diagrams: false,
    created_at: '2026-09-18T00:00:00Z',
    updated_at: '2026-10-05T00:00:00Z',
  },
  {
    id: 'p7',
    title: 'Zero-Trust Cloud File Vault with End-to-End Client Encryption',
    slug: 'zero-trust-cloud-file-vault-it',
    branch: 'IT',
    category: 'MAJOR_FINAL_YEAR',
    short_description: 'AES-256-GCM client-side encrypted cloud storage app with Argon2id password hashing, shamir secret sharing, & WebAuthn biometric login.',
    full_description: `Perfect for IT & Cybersecurity majors. Implements zero-knowledge cryptography where server never sees unencrypted raw files or keys. Includes WebAuthn passkeys support, automated file chunking, public link sharing with expiry, and complete security review document.`,
    tech_stack: ['TypeScript', 'Next.js', 'Web Crypto API', 'Supabase', 'Tailwind', 'AES-256'],
    price_inr: 2199,
    discounted_price_inr: 1399,
    thumbnail_url: '/images/it_zero_trust.jpg',
    demo_video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    file_path: 'projects/it-zero-trust-vault.zip',
    is_published: true,
    is_featured: false,
    view_count: 650,
    download_count: 38,
    includes_report: true,
    includes_ppt: true,
    includes_diagrams: true,
    created_at: '2026-09-20T00:00:00Z',
    updated_at: '2026-10-06T00:00:00Z',
  },
  {
    id: 'p8',
    title: 'Full-Stack E-Commerce Shopping Website & Order System',
    slug: 'full-stack-e-commerce-shopping-website',
    branch: 'CSE',
    category: 'MAJOR_FINAL_YEAR',
    short_description: 'Online shopping platform with product catalog, cart management, checkout order workflow, and secure user authentication.',
    full_description: `Comprehensive web application for CSE & IT students. Includes dynamic product searching, shopping cart state management, user login/signup auth, admin order tracking dashboard, IEEE report, and PPT.`,
    tech_stack: ['React', 'Node.js', 'Express', 'MongoDB', 'Tailwind CSS'],
    price_inr: 1499,
    discounted_price_inr: 999,
    thumbnail_url: '/images/cse_microservices.jpg',
    demo_video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    file_path: 'projects/cse-ecommerce.zip',
    is_published: true,
    is_featured: true,
    view_count: 1540,
    download_count: 98,
    includes_report: true,
    includes_ppt: true,
    includes_diagrams: true,
    created_at: '2026-09-22T00:00:00Z',
    updated_at: '2026-10-06T00:00:00Z',
  },
  {
    id: 'p9',
    title: 'Online Job Portal & Student Career Placement System',
    slug: 'online-job-portal-placement-system',
    branch: 'IT',
    category: 'MAJOR_FINAL_YEAR',
    short_description: 'Platform where students can search for job openings, build profiles, and recruiters can post drives and screen applicants.',
    full_description: `Complete portal for IT & CSE final year project submissions. Features student resume upload, recruiter job postings, application status tracking, automated email alerts, Word report, and presentation slides.`,
    tech_stack: ['Next.js', 'TypeScript', 'PostgreSQL', 'Tailwind', 'Prisma'],
    price_inr: 1499,
    discounted_price_inr: 999,
    thumbnail_url: '/images/it_zero_trust.jpg',
    demo_video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    file_path: 'projects/it-job-portal.zip',
    is_published: true,
    is_featured: true,
    view_count: 1290,
    download_count: 82,
    includes_report: true,
    includes_ppt: true,
    includes_diagrams: true,
    created_at: '2026-09-24T00:00:00Z',
    updated_at: '2026-10-06T00:00:00Z',
  },
  {
    id: 'p10',
    title: 'College Student Placement & Campus Recruitment System',
    slug: 'student-placement-campus-recruitment-system',
    branch: 'CSE',
    category: 'MAJOR_FINAL_YEAR',
    short_description: 'Manages student academic profiles, company eligibility criteria, drive scheduling, and campus placement selection analytics.',
    full_description: `Specialized campus placement management software for engineering colleges. Automates CGPA eligibility filtering, shortlisted candidate exports, company drive scheduling, IEEE format documentation, and viva PPT deck.`,
    tech_stack: ['Python', 'Django', 'SQLite', 'Bootstrap', 'Chart.js'],
    price_inr: 1499,
    discounted_price_inr: 999,
    thumbnail_url: '/images/cseds_churn.jpg',
    demo_video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    file_path: 'projects/cse-placement-system.zip',
    is_published: true,
    is_featured: false,
    view_count: 1110,
    download_count: 74,
    includes_report: true,
    includes_ppt: true,
    includes_diagrams: true,
    created_at: '2026-09-25T00:00:00Z',
    updated_at: '2026-10-06T00:00:00Z',
  },
  {
    id: 'p11',
    title: 'College Event Management & Student Registration Portal',
    slug: 'college-event-management-registration-portal',
    branch: 'IT',
    category: 'MINI_PROJECT',
    short_description: 'Allows colleges to create campus events, workshops, and fests, enabling students to register and download event passes.',
    full_description: `Ideal mini project for IT and Diploma students. Features event creation dashboard, student QR ticket generation, registration count tracking, full source code, and project documentation.`,
    tech_stack: ['PHP', 'MySQL', 'HTML5', 'CSS3', 'JavaScript'],
    price_inr: 1299,
    discounted_price_inr: 799,
    thumbnail_url: '/images/cse_microservices.jpg',
    demo_video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    file_path: 'projects/it-event-management.zip',
    is_published: true,
    is_featured: false,
    view_count: 940,
    download_count: 61,
    includes_report: true,
    includes_ppt: true,
    includes_diagrams: false,
    created_at: '2026-09-26T00:00:00Z',
    updated_at: '2026-10-06T00:00:00Z',
  },
  {
    id: 'p12',
    title: 'Online Learning Platform & Course Progress Tracking System',
    slug: 'online-learning-platform-course-tracking',
    branch: 'CSE',
    category: 'MAJOR_FINAL_YEAR',
    short_description: 'E-learning system providing structured video courses, interactive quizzes, student progress tracking, and completion certificates.',
    full_description: `Full-featured online education platform. Includes instructor course creation, video lecture player, automated quiz scoring, progress completion bar, IEEE project report, and viva presentation slides.`,
    tech_stack: ['React', 'Node.js', 'MongoDB', 'Express', 'JWT'],
    price_inr: 1699,
    discounted_price_inr: 1099,
    thumbnail_url: '/images/aiml_medical_xray.jpg',
    demo_video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    file_path: 'projects/cse-learning-platform.zip',
    is_published: true,
    is_featured: true,
    view_count: 1620,
    download_count: 105,
    includes_report: true,
    includes_ppt: true,
    includes_diagrams: true,
    created_at: '2026-09-27T00:00:00Z',
    updated_at: '2026-10-06T00:00:00Z',
  },
  {
    id: 'p13',
    title: 'Digital Library Management System with Due Date Alerts',
    slug: 'digital-library-management-system',
    branch: 'IT',
    category: 'MINI_PROJECT',
    short_description: 'Manages book inventories, student membership records, book issue/return tracking, and fine calculation.',
    full_description: `Classic database mini project for IT and CSE students. Features ISBN book lookup, member history logs, overdue fine alerts, clean UI dashboard, source code, and project report.`,
    tech_stack: ['Python', 'Tkinter', 'SQLite', 'ReportLab'],
    price_inr: 999,
    discounted_price_inr: 599,
    thumbnail_url: '/images/it_zero_trust.jpg',
    demo_video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    file_path: 'projects/it-library-system.zip',
    is_published: true,
    is_featured: false,
    view_count: 1850,
    download_count: 130,
    includes_report: true,
    includes_ppt: true,
    includes_diagrams: false,
    created_at: '2026-09-28T00:00:00Z',
    updated_at: '2026-10-06T00:00:00Z',
  },
  {
    id: 'p14',
    title: 'Hospital Management & Patient Billing Record System',
    slug: 'hospital-management-patient-billing-system',
    branch: 'CSE',
    category: 'MAJOR_FINAL_YEAR',
    short_description: 'Manages patient admissions, doctor appointment scheduling, electronic medical records (EMR), and automated pharmacy billing.',
    full_description: `Comprehensive healthcare administration system for final-year engineering evaluation. Features multi-role dashboards (Admin, Doctor, Receptionist), appointment booking, billing invoice generation, IEEE format report, and PPT.`,
    tech_stack: ['Java', 'Spring Boot', 'MySQL', 'Thymeleaf', 'Bootstrap'],
    price_inr: 1799,
    discounted_price_inr: 1199,
    thumbnail_url: '/images/aiml_medical_xray.jpg',
    demo_video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    file_path: 'projects/cse-hospital-management.zip',
    is_published: true,
    is_featured: false,
    view_count: 1340,
    download_count: 89,
    includes_report: true,
    includes_ppt: true,
    includes_diagrams: true,
    created_at: '2026-09-29T00:00:00Z',
    updated_at: '2026-10-06T00:00:00Z',
  },
  {
    id: 'p15',
    title: 'Hostel Room Allocation & Complaint Management System',
    slug: 'hostel-management-room-allocation-system',
    branch: 'IT',
    category: 'MINI_PROJECT',
    short_description: 'Handles student room allocations, fee payments, maintenance complaints logging, and warden notice management.',
    full_description: `Practical campus management mini project for IT & Diploma students. Includes room vacancy tracking, maintenance issue tickets, fee receipt generation, source code, and documentation.`,
    tech_stack: ['PHP', 'MySQL', 'JavaScript', 'Tailwind CSS'],
    price_inr: 1199,
    discounted_price_inr: 699,
    thumbnail_url: '/images/ece_smart_agri.jpg',
    demo_video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    file_path: 'projects/it-hostel-management.zip',
    is_published: true,
    is_featured: false,
    view_count: 1210,
    download_count: 77,
    includes_report: true,
    includes_ppt: true,
    includes_diagrams: false,
    created_at: '2026-09-30T00:00:00Z',
    updated_at: '2026-10-06T00:00:00Z',
  },
  {
    id: 'p16',
    title: 'Online Food Ordering & Delivery Tracking System',
    slug: 'online-food-ordering-delivery-system',
    branch: 'CSE',
    category: 'MINI_PROJECT',
    short_description: 'Online platform for browsing restaurant menus, adding custom food items to cart, placing orders, and live status tracking.',
    full_description: `Engaging web mini project for CSE & IT students. Includes interactive menu filters, cart total calculation, order status progress bar, database scripts, report, and slides.`,
    tech_stack: ['React', 'Firebase', 'Tailwind CSS', 'JavaScript'],
    price_inr: 1399,
    discounted_price_inr: 899,
    thumbnail_url: '/images/cse_microservices.jpg',
    demo_video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    file_path: 'projects/cse-food-ordering.zip',
    is_published: true,
    is_featured: false,
    view_count: 1450,
    download_count: 94,
    includes_report: true,
    includes_ppt: true,
    includes_diagrams: false,
    created_at: '2026-10-01T00:00:00Z',
    updated_at: '2026-10-06T00:00:00Z',
  },
  {
    id: 'p17',
    title: 'Automated Professional Resume Builder with PDF Export',
    slug: 'automated-resume-builder-pdf-export',
    branch: 'IT',
    category: 'MINI_PROJECT',
    short_description: 'Generates professional ATS-friendly resumes based on user input details and downloadable customizable templates.',
    full_description: `Useful utility mini project for IT & CSE students. Features real-time resume live preview, custom section reordering, one-click PDF downloading, clean source code, and project report.`,
    tech_stack: ['Next.js', 'React', 'jspdf', 'Tailwind CSS'],
    price_inr: 999,
    discounted_price_inr: 599,
    thumbnail_url: '/images/cseds_churn.jpg',
    demo_video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    file_path: 'projects/it-resume-builder.zip',
    is_published: true,
    is_featured: false,
    view_count: 1670,
    download_count: 118,
    includes_report: true,
    includes_ppt: true,
    includes_diagrams: false,
    created_at: '2026-10-02T00:00:00Z',
    updated_at: '2026-10-06T00:00:00Z',
  },
  {
    id: 'p18',
    title: 'AI Resume Screening & Candidate Matcher System',
    slug: 'ai-resume-screening-candidate-matcher',
    branch: 'AI_DS',
    category: 'MAJOR_FINAL_YEAR',
    short_description: 'An AI-based system that analyzes resumes using Natural Language Processing (NLP) and matches candidates with suitable job requirements.',
    full_description: `AI & Data Science final-year project system. Parses PDF/Word resumes, extracts key skills & experience, calculates job-candidate similarity score using TF-IDF and Cosine Similarity, displays ranking dashboard, includes full IEEE report, and presentation deck.`,
    tech_stack: ['Python', 'Flask', 'Machine Learning', 'NLP', 'SQL', 'Scikit-Learn'],
    price_inr: 1499,
    discounted_price_inr: 999,
    thumbnail_url: '/images/aids_drowsiness.jpg',
    demo_video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    file_path: 'projects/aids-ai-resume-screening.zip',
    is_published: true,
    is_featured: true,
    view_count: 1980,
    download_count: 142,
    includes_report: true,
    includes_ppt: true,
    includes_diagrams: true,
    created_at: '2026-10-03T00:00:00Z',
    updated_at: '2026-10-07T00:00:00Z',
  },
  {
    id: 'p19',
    title: 'Student Academic Performance Prediction & Risk Analytics',
    slug: 'student-performance-prediction-analytics',
    branch: 'AI_DS',
    category: 'MAJOR_FINAL_YEAR',
    short_description: 'Predicts student performance using academic marks and behavioral engagement data with Random Forest machine learning classifier.',
    full_description: `Educational analytics system tailored for AI&DS and CSE students. Features early warning prediction for at-risk students, feature importance visualization, Streamlit web app, IEEE report, and presentation slides.`,
    tech_stack: ['Python', 'Scikit-Learn', 'Pandas', 'Streamlit', 'Random Forest'],
    price_inr: 1499,
    discounted_price_inr: 999,
    thumbnail_url: '/images/cseds_churn.jpg',
    demo_video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    file_path: 'projects/aids-student-prediction.zip',
    is_published: true,
    is_featured: false,
    view_count: 1410,
    download_count: 91,
    includes_report: true,
    includes_ppt: true,
    includes_diagrams: true,
    created_at: '2026-10-04T00:00:00Z',
    updated_at: '2026-10-07T00:00:00Z',
  },
  {
    id: 'p20',
    title: 'Fake News Detection & Fact Verification System',
    slug: 'fake-news-detection-fact-verification',
    branch: 'AIML',
    category: 'MAJOR_FINAL_YEAR',
    short_description: 'Uses machine learning and Natural Language Processing (NLP) to classify news articles as authentic or potentially fake.',
    full_description: `NLP project designed for AIML and CSE students. Utilizes PassiveAggressiveClassifier with TF-IDF vectorization to detect online misinformation. Includes Flask API, web interface, IEEE project report, and PPT deck.`,
    tech_stack: ['Python', 'NLP', 'PassiveAggressiveClassifier', 'Flask', 'TfidfVectorizer'],
    price_inr: 1499,
    discounted_price_inr: 999,
    thumbnail_url: '/images/aiml_medical_xray.jpg',
    demo_video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    file_path: 'projects/aiml-fake-news.zip',
    is_published: true,
    is_featured: true,
    view_count: 1730,
    download_count: 115,
    includes_report: true,
    includes_ppt: true,
    includes_diagrams: true,
    created_at: '2026-10-04T00:00:00Z',
    updated_at: '2026-10-07T00:00:00Z',
  },
  {
    id: 'p21',
    title: 'Social Media Sentiment Analysis & Emotion Classification',
    slug: 'social-media-sentiment-analysis',
    branch: 'AI_DS',
    category: 'MINI_PROJECT',
    short_description: 'Analyzes user text reviews and tweets to identify positive, negative, or neutral sentiment in real-time.',
    full_description: `Popular mini project for AI&DS and CSE students. Features VADER lexicon and NLTK sentiment scoring, live tweet stream analysis, clean charts dashboard, source code, and project report.`,
    tech_stack: ['Python', 'NLTK', 'VADER', 'Streamlit', 'Pandas'],
    price_inr: 1199,
    discounted_price_inr: 699,
    thumbnail_url: '/images/aids_drowsiness.jpg',
    demo_video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    file_path: 'projects/aids-sentiment-analysis.zip',
    is_published: true,
    is_featured: false,
    view_count: 1950,
    download_count: 138,
    includes_report: true,
    includes_ppt: true,
    includes_diagrams: false,
    created_at: '2026-10-04T00:00:00Z',
    updated_at: '2026-10-07T00:00:00Z',
  },
  {
    id: 'p22',
    title: 'Automated Spam Email & Phishing Detection System',
    slug: 'spam-email-phishing-detection-system',
    branch: 'CSE',
    category: 'MINI_PROJECT',
    short_description: 'Detects unwanted spam and phishing emails using Multinomial Naive Bayes machine learning techniques.',
    full_description: `Lightweight cybersecurity mini project for CSE & IT students. Includes text preprocessing, bag-of-words model, desktop GUI, clean source code, and documentation.`,
    tech_stack: ['Python', 'Naive Bayes', 'Scikit-Learn', 'Tkinter'],
    price_inr: 999,
    discounted_price_inr: 599,
    thumbnail_url: '/images/it_zero_trust.jpg',
    demo_video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    file_path: 'projects/cse-spam-detection.zip',
    is_published: true,
    is_featured: false,
    view_count: 1520,
    download_count: 104,
    includes_report: true,
    includes_ppt: true,
    includes_diagrams: false,
    created_at: '2026-10-05T00:00:00Z',
    updated_at: '2026-10-07T00:00:00Z',
  },
  {
    id: 'p23',
    title: 'Real Estate House Price Prediction Engine',
    slug: 'real-estate-house-price-prediction',
    branch: 'CSE_DS',
    category: 'MINI_PROJECT',
    short_description: 'Predicts property market valuation based on location, square footage, bedrooms, and amenities using XGBoost regression.',
    full_description: `Essential Data Science mini project for CSE (DS) and AI&DS students. Features EDA data visualization notebooks, web input form, model evaluation metrics (RMSE, R2 score), source code, and report.`,
    tech_stack: ['Python', 'XGBoost', 'Pandas', 'Flask', 'Matplotlib'],
    price_inr: 1099,
    discounted_price_inr: 699,
    thumbnail_url: '/images/cseds_churn.jpg',
    demo_video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    file_path: 'projects/cseds-house-price.zip',
    is_published: true,
    is_featured: false,
    view_count: 1680,
    download_count: 112,
    includes_report: true,
    includes_ppt: true,
    includes_diagrams: false,
    created_at: '2026-10-05T00:00:00Z',
    updated_at: '2026-10-07T00:00:00Z',
  },
  {
    id: 'p24',
    title: 'Personalized E-Commerce Product Recommendation System',
    slug: 'product-recommendation-system',
    branch: 'AI_DS',
    category: 'MAJOR_FINAL_YEAR',
    short_description: 'Recommends products based on user browsing history and collaborative filtering matrix factorization.',
    full_description: `Advanced Recommendation Engine for AI&DS and CSE final-year students. Combines content-based filtering with SVD matrix factorization, React frontend UI, FastAPI backend, IEEE report, and PPT.`,
    tech_stack: ['Python', 'Collaborative Filtering', 'Surprise', 'FastAPI', 'React'],
    price_inr: 1599,
    discounted_price_inr: 999,
    thumbnail_url: '/images/cse_microservices.jpg',
    demo_video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    file_path: 'projects/aids-product-recommendation.zip',
    is_published: true,
    is_featured: true,
    view_count: 1810,
    download_count: 125,
    includes_report: true,
    includes_ppt: true,
    includes_diagrams: true,
    created_at: '2026-10-05T00:00:00Z',
    updated_at: '2026-10-07T00:00:00Z',
  },
  {
    id: 'p25',
    title: 'Automated Face Recognition Attendance Management System',
    slug: 'face-recognition-attendance-system',
    branch: 'AIML',
    category: 'MAJOR_FINAL_YEAR',
    short_description: 'Automatically records student classroom attendance using OpenCV facial recognition and webcam live feed.',
    full_description: `High-demand Computer Vision project for AIML, CSE, and IT final year. Features real-time face embedding matching, automated CSV/Excel attendance export, desktop GUI dashboard, IEEE report, and presentation slides.`,
    tech_stack: ['Python', 'OpenCV', 'face_recognition', 'SQLite', 'Tkinter'],
    price_inr: 1799,
    discounted_price_inr: 1199,
    thumbnail_url: '/images/aids_drowsiness.jpg',
    demo_video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    file_path: 'projects/aiml-face-attendance.zip',
    is_published: true,
    is_featured: true,
    view_count: 2450,
    download_count: 178,
    includes_report: true,
    includes_ppt: true,
    includes_diagrams: true,
    created_at: '2026-10-05T00:00:00Z',
    updated_at: '2026-10-07T00:00:00Z',
  },
  {
    id: 'p26',
    title: 'Real-Time Helmet Detection & Traffic Safety System',
    slug: 'helmet-detection-computer-vision-system',
    branch: 'AIML',
    category: 'MAJOR_FINAL_YEAR',
    short_description: 'Detects whether motorcyclists are wearing safety helmets using YOLOv8 object detection on traffic video streams.',
    full_description: `Cutting-edge vision AI project for AIML and CSE students. Trains YOLOv8 model on custom helmet datasets, detects non-compliant riders, crops license plates, generates violation logs, includes full IEEE report, and PPT.`,
    tech_stack: ['Python', 'YOLOv8', 'OpenCV', 'PyTorch', 'FastAPI'],
    price_inr: 1999,
    discounted_price_inr: 1299,
    thumbnail_url: '/images/hero_engineering_lab.jpg',
    demo_video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    file_path: 'projects/aiml-helmet-detection.zip',
    is_published: true,
    is_featured: true,
    view_count: 2120,
    download_count: 154,
    includes_report: true,
    includes_ppt: true,
    includes_diagrams: true,
    created_at: '2026-10-06T00:00:00Z',
    updated_at: '2026-10-07T00:00:00Z',
  },
  {
    id: 'p27',
    title: 'College AI Assistant Chatbot with RAG Knowledge Base',
    slug: 'college-ai-assistant-chatbot-rag',
    branch: 'AI_DS',
    category: 'MAJOR_FINAL_YEAR',
    short_description: 'Answers student queries about departments, faculty, timetable, syllabus, and college admission rules using LangChain and RAG.',
    full_description: `Generative AI RAG project for AI&DS and CSE final-year evaluation. Embeds college handbooks into FAISS vector database, retrieves accurate answers with source citations, Streamlit chat interface, IEEE report, and PPT deck.`,
    tech_stack: ['Python', 'LangChain', 'OpenAI', 'FAISS', 'Streamlit'],
    price_inr: 1699,
    discounted_price_inr: 1099,
    thumbnail_url: '/images/aiml_medical_xray.jpg',
    demo_video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    file_path: 'projects/aids-college-chatbot.zip',
    is_published: true,
    is_featured: true,
    view_count: 2210,
    download_count: 165,
    includes_report: true,
    includes_ppt: true,
    includes_diagrams: true,
    created_at: '2026-10-06T00:00:00Z',
    updated_at: '2026-10-07T00:00:00Z',
  },
  {
    id: 'p28',
    title: 'PDF Document Question Answering System (LangChain & Vector DB)',
    slug: 'pdf-document-question-answering-system',
    branch: 'AI_DS',
    category: 'MAJOR_FINAL_YEAR',
    short_description: 'Allows users to upload custom PDF documents and ask natural language questions with precise context citations.',
    full_description: `Popular Generative AI project for AI&DS, CSE, and IT students. Uses LangChain document loaders, recursive text chunking, Chroma vector store, Next.js frontend UI, full documentation, and viva presentation deck.`,
    tech_stack: ['Python', 'LangChain', 'PyPDF2', 'ChromaDB', 'Next.js'],
    price_inr: 1799,
    discounted_price_inr: 1199,
    thumbnail_url: '/images/it_zero_trust.jpg',
    demo_video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    file_path: 'projects/aids-pdf-qa-system.zip',
    is_published: true,
    is_featured: true,
    view_count: 2390,
    download_count: 182,
    includes_report: true,
    includes_ppt: true,
    includes_diagrams: true,
    created_at: '2026-10-06T00:00:00Z',
    updated_at: '2026-10-07T00:00:00Z',
  },
  {
    id: 'p29',
    title: 'AI Study Assistant & Automated Exam Question Generator',
    slug: 'ai-study-assistant-exam-generator',
    branch: 'AI_DS',
    category: 'MAJOR_FINAL_YEAR',
    short_description: 'Helps students understand complex topics, generates practice quizzes, flashcards, and step-by-step topic summaries.',
    full_description: `EduTech GenAI system for AI&DS and CSE. Integrates Llama-3 / GPT models to create custom practice tests from syllabus text, flashcards export, interactive web interface, IEEE format report, and PPT.`,
    tech_stack: ['Python', 'Llama-3', 'LangChain', 'FastAPI', 'React'],
    price_inr: 1599,
    discounted_price_inr: 999,
    thumbnail_url: '/images/cseds_churn.jpg',
    demo_video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    file_path: 'projects/aids-ai-study-assistant.zip',
    is_published: true,
    is_featured: false,
    view_count: 1740,
    download_count: 119,
    includes_report: true,
    includes_ppt: true,
    includes_diagrams: true,
    created_at: '2026-10-06T00:00:00Z',
    updated_at: '2026-10-07T00:00:00Z',
  },
  {
    id: 'p30',
    title: 'AI Technical & HR Interview Practice Simulator',
    slug: 'ai-interview-practice-simulator',
    branch: 'AI_DS',
    category: 'MAJOR_FINAL_YEAR',
    short_description: 'Interactive voice & text AI bot that conducts mock technical & HR interviews with real-time feedback scores.',
    full_description: `Next-gen career prep system for AI&DS and CSE students. Conducts role-specific mock interviews, evaluates answer accuracy & confidence, provides improvement report, includes IEEE paper, and PPT deck.`,
    tech_stack: ['Python', 'SpeechRecognition', 'GPT-4', 'Next.js', 'Web Speech API'],
    price_inr: 1699,
    discounted_price_inr: 1099,
    thumbnail_url: '/images/aids_drowsiness.jpg',
    demo_video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    file_path: 'projects/aids-ai-interview-bot.zip',
    is_published: true,
    is_featured: true,
    view_count: 1980,
    download_count: 145,
    includes_report: true,
    includes_ppt: true,
    includes_diagrams: true,
    created_at: '2026-10-06T00:00:00Z',
    updated_at: '2026-10-07T00:00:00Z',
  },
  {
    id: 'p31',
    title: 'AI Customer Support Knowledge Base Chatbot',
    slug: 'ai-customer-support-knowledge-base-chatbot',
    branch: 'CSE',
    category: 'MAJOR_FINAL_YEAR',
    short_description: 'Provides automated answers to customer support tickets using Pinecone vector search and LLM contextual synthesis.',
    full_description: `Enterprise GenAI application for CSE & IT final year. Features ticket routing, vector similarity search on support docs, fallback human escalation triggers, Next.js UI, report, and slides.`,
    tech_stack: ['TypeScript', 'Next.js', 'Pinecone', 'LangChain', 'Tailwind'],
    price_inr: 1499,
    discounted_price_inr: 999,
    thumbnail_url: '/images/cse_microservices.jpg',
    demo_video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    file_path: 'projects/cse-customer-support-ai.zip',
    is_published: true,
    is_featured: false,
    view_count: 1530,
    download_count: 99,
    includes_report: true,
    includes_ppt: true,
    includes_diagrams: true,
    created_at: '2026-10-07T00:00:00Z',
    updated_at: '2026-10-07T00:00:00Z',
  },
  {
    id: 'p32',
    title: 'AI Research Paper Summarizer & Key Findings Extractor',
    slug: 'ai-research-paper-summarizer',
    branch: 'AI_DS',
    category: 'MAJOR_FINAL_YEAR',
    short_description: 'Searches arXiv research papers, extracts methodology summaries, key findings, and generates literature review drafts.',
    full_description: `Academic research tool for AI&DS and CSE students. Fetches research PDFs from arXiv API, generates concise executive summaries, compares paper methodologies, includes full IEEE report, and PPT.`,
    tech_stack: ['Python', 'LangChain', 'ArXiv API', 'Streamlit', 'HuggingFace'],
    price_inr: 1799,
    discounted_price_inr: 1199,
    thumbnail_url: '/images/cseds_churn.jpg',
    demo_video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    file_path: 'projects/aids-research-paper-summarizer.zip',
    is_published: true,
    is_featured: false,
    view_count: 1640,
    download_count: 108,
    includes_report: true,
    includes_ppt: true,
    includes_diagrams: true,
    created_at: '2026-10-07T00:00:00Z',
    updated_at: '2026-10-07T00:00:00Z',
  },
  {
    id: 'p33',
    title: 'AI Coding Assistant & Syntax Error Debugger',
    slug: 'ai-coding-assistant-error-debugger',
    branch: 'CSE',
    category: 'MAJOR_FINAL_YEAR',
    short_description: 'Analyzes code snippets, identifies runtime bugs, generates code refactoring suggestions, and explains complex algorithms.',
    full_description: `Developer productivity project for CSE & IT students. Uses local CodeLlama via Ollama or LLM API to provide inline code explanations, unit test generation, bug fixes, IEEE report, and presentation deck.`,
    tech_stack: ['TypeScript', 'VS Code Extension API', 'Ollama', 'CodeLlama', 'Node.js'],
    price_inr: 1699,
    discounted_price_inr: 1099,
    thumbnail_url: '/images/cse_microservices.jpg',
    demo_video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    file_path: 'projects/cse-ai-coding-assistant.zip',
    is_published: true,
    is_featured: true,
    view_count: 2180,
    download_count: 162,
    includes_report: true,
    includes_ppt: true,
    includes_diagrams: true,
    created_at: '2026-10-07T00:00:00Z',
    updated_at: '2026-10-07T00:00:00Z',
  },
  {
    id: 'p34',
    title: 'AI Resume & Job Description Matcher with Gap Analysis',
    slug: 'ai-resume-job-matcher-gap-analysis',
    branch: 'CSE_DS',
    category: 'MAJOR_FINAL_YEAR',
    short_description: 'Compares candidate resumes with job postings, computes similarity embeddings, and highlights missing key skills.',
    full_description: `Career analytics project for CSE (DS) and AI&DS students. Uses OpenAI text embeddings to compare resume text against target job descriptions, outputs percentage fit score + missing skill recommendations, full report, and PPT.`,
    tech_stack: ['Python', 'OpenAI Embeddings', 'Pandas', 'Streamlit', 'PDFMiner'],
    price_inr: 1599,
    discounted_price_inr: 999,
    thumbnail_url: '/images/aids_drowsiness.jpg',
    demo_video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    file_path: 'projects/cseds-resume-job-matcher.zip',
    is_published: true,
    is_featured: false,
    view_count: 1820,
    download_count: 129,
    includes_report: true,
    includes_ppt: true,
    includes_diagrams: true,
    created_at: '2026-10-07T00:00:00Z',
    updated_at: '2026-10-07T00:00:00Z',
  }
];
